FROM ruby:3.2

ENV RAILS_ENV=development
ENV RACK_ENV=development

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  nodejs \
  postgresql-client \
  git \
  curl \
  vim \
  less

RUN apt-get update && apt-get install -y ffmpeg
WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
