default: &default
  adapter: postgresql
  encoding: unicode
  username: caioprieto
  password: ca23io04
  host: db
  pool: 5

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
